### ISSUE TITLE
Data source switch to Rail Data Marketplace

### ISSUE THREAD

**Issue by geofurlong** [geofurlong/builder#3]
Network Rail now publishes the geospatial datasets for ELR centre-lines and Mileposts on the [Rail Data Marketplace](https://raildata.org.uk/) under the title `NWR Track Model`. A number of changes to the build process source code, intermediate output files, and databases require updating as a consequence.

- ELR base filename renamed to `NWR_ELRs`
- ELR column `L_SYSTEM` deleted
- ELR column `SHAPE_LEN` deleted
- ELR column `VERSION` (double) added
- ELR column `EXTRACTED` (date) added
- MILEPOST base filename renamed to `NWR_Waymarks`
- MILEPOST column `M_SYSTEM` renamed `UNIT`
- MILEPOST column `WAYMARK_VA` renamed `VALUE`
- MILEPOST column `VERSION` (double) added
- MILEPOST column `EXTRACTED` (date) added

The measurement unit of the ELR, which was previously included as column `L_SYSTEM`, now needs to be read from the MILEPOST dataset.

The ELR geometry length needs to be measured, instead of using the input dataset value.

An initial review of the current dataset (30/07/24) has noticeable changes to the reported extents and / or geometry lengths of the following ELRs: `ALK, AMJ, CMD2, CRL, DJO2, FNS1, FNS1, FSS2, FSS3, ROT, RYH2, SAW, SAW, THN, TJC3, TRL1, TRL6, TRL7`.

The current dataset includes three new ELRs: `EPS, ESJ, FJS`. It appears that only `EPS` will be included in the build output, as ELRs `ESJ` and `FJS` are contained within `TRL5` and `FJS` respectively.

**Comment by pelter** [comment]
Complete via commit  `6a24b88`.

**Comment by geofurlong** [comment]
Completed via commit `6a24b88`.
